services:
  db:
    image: mariadb:latest
    container_name: transit-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transit
      MYSQL_USER: transit_user
      MYSQL_PASSWORD: transit_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./dev/transit-back
    container_name: transit-back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./dev/transit-back:/var/www
      - ./database:/tmp/sql_scripts
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: transit
      DB_USERNAME: transit_user
      DB_PASSWORD: transit_pass

    command: >
      sh -c "
      echo '--- Vérification .env ---' &&
      if [ ! -f .env ]; then cp .env.example .env && php artisan key:generate; fi &&

      echo '--- Installation Composer ---' &&
      composer install --no-interaction --prefer-dist &&

      echo '--- Attente DB ---' &&
      sleep 10 &&

      echo '--- Migration Laravel ---' &&
      php artisan migrate --force &&

      echo '--- Injection SQL ---' &&
      mariadb -h db -u transit_user -ptransit_pass transit < /tmp/sql_scripts/1_create.sql ;
      mariadb -h db -u transit_user -ptransit_pass transit < /tmp/sql_scripts/2_alter-table.sql ;
      mariadb -h db -u transit_user -ptransit_pass transit < /tmp/sql_scripts/3_insert.sql ;

      echo '--- Démarrage Laravel ---' &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    healthcheck:
      test: "curl -f http://localhost:8000 || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s

  frontend:
    build: ./dev/transit-front
    container_name: transit-front
    ports:
      - "3000:3000"
    volumes:
      - ./dev/transit-front:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: http://localhost:8000

volumes:
  db_data:
